version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "async-shreyas"
    assignees:
      - "async-shreyas"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "typescript"
        versions: ["5.x"]